### ISSUE TITLE
Problem when create more than one api client

### ISSUE THREAD

**Issue by ehsanehsani** [0xaryan/KuttSharp#1]
when i create a new `KuttSharpApi`client and add key (as header) its ok for first request
 but if i call my method again and create a new `KuttSharpApi` again i receive this error:
reCAPTCHA is not valid. Try again.
after search and test the source code i recognized for each call a new "X-API-Key" item adds to header and i think the following code before add the header will fix it:

`if (!client.DefaultRequestHeaders.Contains("X-API-Key"))`

**Comment by 0xaryan** [comment]
Oh, what a mess!
Thank you for the report, can you please submit a PR for this issue?

**Comment by 0xaryan** [comment]
Fixed in #2
